on:
  pull_request:
    branches:
      - main

jobs:
  build_app:
    permissions:
      contents: read
      actions: read
    runs-on: ubuntu-latest
    name: test shared components
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node Install
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm exec nx run budgie-app:build
